server:
  port: 8001
  servlet:
    context-path: /zkservice
spring:
  application:
    name: zkservice
  cloud:
    zookeeper:
      connect-string: 192.168.56.103:2181
logging:
  level:
    org.apache.zookeeper.ClientCnxn: WARN